### ISSUE TITLE
Hi, I can't find the images_test.txt and bounding_boxes_test.txt in Birds-200-2011 dataset，where are them？

### ISSUE THREAD

**Issue by renyuzh** [halwai/bird_classification#1]

**Comment by halwai** [comment]
Hey 
1) The dataset can be found [here](http://www.vision.caltech.edu/visipedia/CUB-200-2011.html). Updated README.md reflects the same.
2) There is additional information provided  (such as segmentation)  which I have not used
3) Additionally the code has some bugs and the results are a little less then expected. I will try to modify them as I find more time.

**Comment by renyuzh** [comment]
Thanks for your anwer.  But I have downloaded the dataset, there are "attributes  bounding_boxes.txt  classes.txt  image_class_labels.txt  images  images.txt  parts  train_test_split.txt" in the dataset. The bounding_boxes.txt, images.txt and image_class_labels.txt are the train file you used in bird_dataset_generator.py, howerver, images_test.txt and bounding_boxes_test.txt  are not in the dataset.

**Comment by halwai** [comment]
Uploaded the required files in the "/data" folder.

**Comment by 8ANDfinalrule** [comment]
Hey, what about the images_train.txt bounding_boxes_train.txt files? Should i use train_generator  to create them?

**Comment by halwai** [comment]
It seems that the dataset I downloaded and the one present in the UCSD website are a little different in terms of their structure (the data is still the same).  This is evident from the Dataset-Readme file ( in "/dataset-readme") and the Caltech Dataset-Readme file (http://www.vision.caltech.edu/visipedia-data/CUB-200-2011/README.txt). 

But this issue is easily solvable. Use "train_test_split.txt", "images.txt" to get the files images_train.txt and images_test.txt. Similarly use "train_test_split","bounding_boxes.txt" to get bounding_boxes_train.txt and bounding_boxes_test.txt.

Apologies for the wrong dataset information earlier and I will update the code to reflect the original dataset in a week.

**Comment by halwai** [comment]
Hey @8ANDfinalrule  please go through the update README . Let me know if the issue is resolved.

**Comment by 8ANDfinalrule** [comment]
Hey, I was busy for some time, thanks for fixing this one. I am afraid there's also vgg16_weights.npz missing. Attempt to run the main.py ends with missing file error.

**Comment by halwai** [comment]
Hey its a very well known file. You can use the following link to find the same.
http://www.cs.toronto.edu/~frossard/post/vgg16/
